# Generated by Django 3.2.12 on 2022-05-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trans',
        ),
    ]
