# Generated by Django 3.2.12 on 2022-05-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_birth',
        ),
    ]
