# Generated by Django 3.2.12 on 2022-05-13 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0002_remove_user_user_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20)),
                ('card_type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('percent', models.IntegerField()),
                ('use_stand', models.TextField()),
                ('month_stand', models.TextField()),
                ('card', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kb_platform.card')),
            ],
            options={
                'db_table': 'kb_platform_benefit',
            },
        ),
    ]
