# Generated by Django 3.2.12 on 2022-05-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0002_delete_trans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('trans_price', models.IntegerField()),
                ('trans_content', models.CharField(max_length=30)),
                ('trans_type', models.CharField(choices=[('0', '식비'), ('1', '이동통신'), ('2', '쇼핑'), ('3', '문화생활'), ('4', '의료'), ('5', '교통비')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='kb_platform.account')),
            ],
        ),
    ]
