# Generated by Django 3.2.12 on 2022-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0003_benefit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
