# Generated by Django 3.2.12 on 2022-05-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0003_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_detail',
            field=models.CharField(choices=[(0, '입출금자유'), (1, '예금/적금/주택청약'), (2, '골드'), (3, '증권')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[(0, '은행'), (1, '증권'), (2, '금')], max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trans',
            name='trans_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trans',
            name='trans_type',
            field=models.CharField(choices=[(0, '식비'), (1, '이동통신'), (2, '쇼핑'), (3, '문화생활'), (4, '의료'), (5, '교통비')], max_length=50),
        ),
    ]
