# Generated by Django 3.2.12 on 2022-05-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0004_card_card_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
