# Generated by Django 3.2.12 on 2022-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0004_auto_20220517_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pred', models.IntegerField()),
                ('act', models.IntegerField()),
            ],
        ),
    ]
