# Generated by Django 3.2.12 on 2022-05-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0006_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='acc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='kb_platform.account'),
        ),
    ]
