# Generated by Django 3.2.12 on 2022-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0007_trans_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='trans_type',
            field=models.CharField(choices=[('0', '식비'), ('1', '이동통신'), ('2', '쇼핑'), ('3', '문화생활'), ('4', '의료'), ('5', '교통비')], max_length=50),
        ),
    ]
