# Generated by Django 3.2.12 on 2022-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_platform', '0008_alter_trans_trans_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[('0', '은행'), ('1', '증권'), ('2', '금')], max_length=50),
        ),
    ]
